[package]
name = "mod_demo"
version = "0.1.0"
authors = ["jtr109 <lyp_login@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "my_mod"
path = "src/lib/mod.rs"

[dependencies]
